/*
 * lcm_channel_names.h
 *
 *  Created on: Mar 13, 2009
 *      Author: abachrac
 */

#ifndef LCM_CHANNEL_NAMES_H_
#define LCM_CHANNEL_NAMES_H_

//define all the lcm chanel names here so

//laser
#define LASER_CHANNEL "LASER"
#define ROBOT_LASER_CHANNEL "ROBOT_LASER"

//scan matcher
#define SCAN_MATCH_POS_CHANNEL "SCAN_MATCH_POS"
#define SCAN_MATCH_REL_CHANNEL "SCAN_MATCH_REL"

//mission
#define MISSION_CONTROL_CHANNEL "MISSION_CONTROL"
#define HEIGHT_SWEEP_CHANNEL "HEIGHT_SWEEP"

//Navigator
#define NAV_PLAN_CHANNEL "NAV_PLAN"
#define NAV_GOAL_CHANNEL "NAV_GOAL"
#define NAV_PLAN_RESULT_CHANNEL "NAV_PLAN_RESULT"
#define NAV_GOAL_LIST_CHANNEL "NAV_GOAL_LIST"

//pose channels
#define POSE_CHANNEL "POSE"
#define POSE_GROUND_TRUTH_CHANNEL "POSE_GROUND_TRUTH"
#define POSE_UNCORRECTED_CHANNEL "POSE_UNCORRECTED"
#define POSE_CORRECTED_CHANNEL "POSE_CORRECTED"
#define STATE_CLOCK_CHANNEL "TIMER_STATE"


//CONTROLLER
#define CONTROL_CHANNEL  "CONTROL_COMMAND"
#define WAYPOINT_COMMAND_CHANNEL "WAYPOINT_COMMAND"
#define WAYPOINT_PLANNER_GOAL_CHANNEL "WAYPOINT_PLANNER_GOAL"
#define WAYPOINT_GOAL_CHANNEL "WAYPOINT_GOAL"
#define WAYPOINT_CURR_CHANNEL "WAYPOINT_CURR"
#define WAYPOINT_IGNORED_CHANNEL "WAYPOINT_IGNORED"
#define SIM_TELEPORT_CHANNEL "SIM_TELEPORT_COMMAND"

#define PLANNED_WAYPOINTS_CHANNEL "PLANNED_WAYPOINTS"

//Comm Loss Planner
#define WAYPOINT_COMM_LOSS_CHANNEL "WAYPOINT_COMM_LOSS"
#define COMM_STATUS_CHANNEL "COMM_STATUS"

//Images
#define IMAGE_STEREO_CHANNEL "IMAGE_STEREO"
#define IMAGE_COLOR_CHANNEL "IMAGE_COLOR"

//Vicon
#define VICON_PREFIX "VICON_"

//logging
#define LOG_ANNOTATE_CHANNEL "LOG_ANNOTATE"

//system vitals
#define SYSTEM_VITALS_CHANNEL "SYSTEM_VITALS"


//SLAM
#define SLAM_POSITION_CHANNEL "SLAM_POSITION"
#define SLAM_TRAJECTORY_CHANNEL "SLAM_TRAJECTORY"


//occupancy PixelMap, voxel map
#define SLAM_MAP_CHANNEL "SLAM_MAP"
#define VOXEL_MAP_CHANNEL "VOXEL_MAP"

// localize
#define LOCALIZE_REINITIALIZE_CHANNEL "LOCALIZE_REINITIALIZE"

//Occupancy Gridmaps
#define MAP_SERVER_MAP_CHANNEL "MAP_SERVER"
#define GMAPPER_GRIDMAP_CHANNEL "GRIDMAP"
#define CAM_GRIDMAP_CHANNEL "CAMMAP"
#define NAVIGATOR_UTILITY_MAP_CHANNEL "NAVIGATOR_UTILITY_MAP"
#define FRONTIER_UTILITY_MAP_CHANNEL "FRONTIER_UTILITY_MAP"
#define CAM_FRONTIER_UTILITY_MAP_CHANNEL "CAM_FRONTIER_UTILITY_MAP"
#define MAP3D_CHANNEL "MAP3D_GRIDMAP"

#endif /* LCM_CHANNEL_NAMES_H_ */
